# Generated by Django 5.2.16 on 2026-07-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='notified_50',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budget',
            name='notified_80',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budget',
            name='notified_90',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budget',
            name='notified_exceeded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budget',
            name='notified_expiring_soon',
            field=models.BooleanField(default=False),
        ),
    ]
