# Generated by Django 5.2.16 on 2026-07-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('invite', 'Invite'), ('login_reminder', 'Login Reminder'), ('budget_exceeded', 'Budget Exceeded'), ('insight', 'Insight'), ('reminder', 'General Reminder'), ('budget_expiring', 'Budget Expiring'), ('new_month', 'New Month')], default='reminder', max_length=30),
        ),
    ]
