# Generated by Django 5.2.16 on 2026-07-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_notification_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='owner',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('invite', 'Invite'), ('login_reminder', 'Login Reminder'), ('budget_exceeded', 'Budget Exceeded'), ('insight', 'Insight'), ('reminder', 'General Reminder'), ('budget_expiring', 'Budget Expiring'), ('new_month', 'New Month')], default='reminder', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
