# Generated by Django 5.2.16 on 2026-07-16 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='notes',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
