# Generated by Django 5.2.16 on 2026-07-17 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_remove_expense_tags_remove_category_is_default_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
    ]
