# Generated by Django 5.2.16 on 2026-07-23 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_recurringexpense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurringexpense',
            old_name='owner',
            new_name='user',
        ),
    ]
