# Generated by Django 5.2.16 on 2026-07-23 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_rename_owner_recurringexpense_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurringexpense',
            old_name='user',
            new_name='owners',
        ),
    ]
