# Generated by Django 5.2.16 on 2026-07-23 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_rename_user_recurringexpense_owners'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringexpense',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='recurringexpense',
            name='owners',
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_expenses', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Bank Transfer', 'Bank Transfer'), ('JazzCash', 'JazzCash'), ('Easypaisa', 'Easypaisa'), ('Other', 'Other')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.category'),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
