# Generated by Django 5.2.16 on 2026-07-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_groupinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_tracked_in_insights',
            field=models.BooleanField(default=False),
        ),
    ]
