# Generated by Django 5.2.16 on 2026-07-22 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_deadline_notified_task_due_time_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='time_spent_minutes',
        ),
        migrations.RemoveField(
            model_name='task',
            name='timer_started_at',
        ),
    ]
