# Generated by Django 5.2.16 on 2026-07-22 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_task_time_spent_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
