# Generated by Django 5.2.16 on 2026-08-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_groupmember_invited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_1h_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_2h_sent',
            field=models.BooleanField(default=False),
        ),
    ]
