# Generated by Django 5.2.16 on 2026-08-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_task_reminder_1h_sent_task_reminder_2h_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_15m_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_30m_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_45m_sent',
            field=models.BooleanField(default=False),
        ),
    ]
